import { Employee, AttendanceRecord, ActivityLog } from '../types';

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'EMP001',
    name: 'Sarah Jenkins',
    email: 's.jenkins@company.com',
    mobile: '+1 (555) 234-5678',
    department: 'Engineering',
    designation: 'Lead Software Architect',
    dateOfJoining: '2021-03-15',
    status: 'Active',
    bankDetails: {
      bankName: 'Chase Bank',
      accountNumber: '•••• •••• 4920',
      ifscCode: 'CHAS000182',
    },
    basicSalary: 95000,
    dearnessAllowance: 10000,
    houseRentAllowance: 15000,
    medicalAllowance: 2000,
    otherAllowances: 5000,
    insuranceContribution: 1500,
    otherDeductions: 500,
    leaveBalance: 12,
  },
  {
    id: 'EMP002',
    name: 'Marcus Vance',
    email: 'm.vance@company.com',
    mobile: '+1 (555) 876-5432',
    department: 'Engineering',
    designation: 'Senior Frontend Developer',
    dateOfJoining: '2022-06-01',
    status: 'Active',
    bankDetails: {
      bankName: 'Bank of America',
      accountNumber: '•••• •••• 8831',
      ifscCode: 'BOFA000912',
    },
    basicSalary: 82000,
    dearnessAllowance: 8000,
    houseRentAllowance: 12000,
    medicalAllowance: 2000,
    otherAllowances: 3000,
    insuranceContribution: 1500,
    otherDeductions: 500,
    leaveBalance: 12,
  },
  {
    id: 'EMP003',
    name: 'Priya Sharma',
    email: 'p.sharma@company.com',
    mobile: '+1 (555) 345-6789',
    department: 'Human Resources',
    designation: 'HR Operations Manager',
    dateOfJoining: '2020-01-10',
    status: 'Active',
    bankDetails: {
      bankName: 'Wells Fargo',
      accountNumber: '•••• •••• 1029',
      ifscCode: 'WFAR000431',
    },
    basicSalary: 72000,
    dearnessAllowance: 7000,
    houseRentAllowance: 10000,
    medicalAllowance: 2000,
    otherAllowances: 2000,
    insuranceContribution: 1500,
    otherDeductions: 0,
    leaveBalance: 12,
  },
  {
    id: 'EMP004',
    name: 'David Chen',
    email: 'd.chen@company.com',
    mobile: '+1 (555) 654-3210',
    department: 'Sales',
    designation: 'Regional Sales Director',
    dateOfJoining: '2019-11-04',
    status: 'Active',
    bankDetails: {
      bankName: 'Citibank',
      accountNumber: '•••• •••• 5543',
      ifscCode: 'CITI000210',
    },
    basicSalary: 88000,
    dearnessAllowance: 9000,
    houseRentAllowance: 13000,
    medicalAllowance: 2000,
    otherAllowances: 4000,
    insuranceContribution: 1500,
    otherDeductions: 0,
    leaveBalance: 12,
  },
  {
    id: 'EMP005',
    name: 'Elena Rostova',
    email: 'e.rostova@company.com',
    mobile: '+1 (555) 432-1098',
    department: 'Marketing',
    designation: 'Growth Marketing Lead',
    dateOfJoining: '2023-02-18',
    status: 'Active',
    bankDetails: {
      bankName: 'Capital One',
      accountNumber: '•••• •••• 7712',
      ifscCode: 'CAPO000554',
    },
    basicSalary: 68000,
    dearnessAllowance: 6500,
    houseRentAllowance: 9500,
    medicalAllowance: 2000,
    otherAllowances: 2000,
    insuranceContribution: 1500,
    otherDeductions: 0,
    leaveBalance: 12,
  },
  {
    id: 'EMP006',
    name: 'James Wilson',
    email: 'j.wilson@company.com',
    mobile: '+1 (555) 901-2345',
    department: 'Finance',
    designation: 'Senior Financial Analyst',
    dateOfJoining: '2022-09-12',
    status: 'Active',
    bankDetails: {
      bankName: 'JPMorgan Chase',
      accountNumber: '•••• •••• 3390',
      ifscCode: 'JPMC000881',
    },
    basicSalary: 78000,
    dearnessAllowance: 7500,
    houseRentAllowance: 11000,
    medicalAllowance: 2000,
    otherAllowances: 3000,
    insuranceContribution: 1500,
    otherDeductions: 0,
    leaveBalance: 12,
  },
  {
    id: 'EMP007',
    name: 'Aisha Patel',
    email: 'a.patel@company.com',
    mobile: '+1 (555) 567-8901',
    department: 'Operations',
    designation: 'Supply Chain Coordinator',
    dateOfJoining: '2023-07-24',
    status: 'Active',
    bankDetails: {
      bankName: 'US Bank',
      accountNumber: '•••• •••• 9921',
      ifscCode: 'USBN000301',
    },
    basicSalary: 62000,
    dearnessAllowance: 6000,
    houseRentAllowance: 9000,
    medicalAllowance: 2000,
    otherAllowances: 1500,
    insuranceContribution: 1500,
    otherDeductions: 0,
    leaveBalance: 12,
  },
  {
    id: 'EMP008',
    name: 'Robert Taylor',
    email: 'r.taylor@company.com',
    mobile: '+1 (555) 678-9012',
    department: 'Engineering',
    designation: 'DevOps Specialist',
    dateOfJoining: '2021-10-05',
    status: 'Inactive',
    bankDetails: {
      bankName: 'PNC Bank',
      accountNumber: '•••• •••• 6102',
      ifscCode: 'PNCB000742',
    },
    basicSalary: 85000,
    dearnessAllowance: 8500,
    houseRentAllowance: 12500,
    medicalAllowance: 2000,
    otherAllowances: 3500,
    insuranceContribution: 1500,
    otherDeductions: 500,
    leaveBalance: 12,
  },
];

const TODAY = new Date().toISOString().split('T')[0];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'ATT-001',
    employeeId: 'EMP001',
    date: TODAY,
    status: 'Present',
    checkInTime: '09:02 AM',
    checkOutTime: '05:30 PM',
    workingHours: 8.5,
    remarks: 'On time',
  },
  {
    id: 'ATT-002',
    employeeId: 'EMP002',
    date: TODAY,
    status: 'Present',
    checkInTime: '08:55 AM',
    checkOutTime: '05:15 PM',
    workingHours: 8.3,
    remarks: 'Punctual',
  },
  {
    id: 'ATT-003',
    employeeId: 'EMP003',
    date: TODAY,
    status: 'Leave',
    checkInTime: '-',
    checkOutTime: '-',
    workingHours: 0,
    remarks: 'Approved Casual Leave',
  },
  {
    id: 'ATT-004',
    employeeId: 'EMP004',
    date: TODAY,
    status: 'Out of Station',
    checkInTime: '09:30 AM',
    checkOutTime: '06:00 PM',
    workingHours: 8.5,
    remarks: 'Onsite Client Visit (New York)',
  },
  {
    id: 'ATT-005',
    employeeId: 'EMP005',
    date: TODAY,
    status: 'Late Arrival',
    checkInTime: '10:15 AM',
    checkOutTime: '06:30 PM',
    workingHours: 8.25,
    remarks: 'Traffic delay acknowledged',
  },
  {
    id: 'ATT-006',
    employeeId: 'EMP006',
    date: TODAY,
    status: 'Half Day',
    checkInTime: '09:00 AM',
    checkOutTime: '01:00 PM',
    workingHours: 4.0,
    remarks: 'Personal appointment afternoon',
  },
  {
    id: 'ATT-007',
    employeeId: 'EMP007',
    date: TODAY,
    status: 'Absent',
    checkInTime: '-',
    checkOutTime: '-',
    workingHours: 0,
    remarks: 'No notification received',
  },
];

export const INITIAL_ACTIVITIES: ActivityLog[] = [
  {
    id: 'ACT-101',
    timestamp: 'Just now',
    type: 'ATTENDANCE_MARKED',
    description: "Today's attendance batch recorded for 7 employees",
  },
  {
    id: 'ACT-102',
    timestamp: '2 hours ago',
    type: 'EMPLOYEE_ADDED',
    description: 'Aisha Patel (EMP007) added to Operations department',
    employeeName: 'Aisha Patel',
    employeeId: 'EMP007',
  },
  {
    id: 'ACT-103',
    timestamp: 'Yesterday at 04:15 PM',
    type: 'EMPLOYEE_UPDATED',
    description: 'Updated designation for Sarah Jenkins to Lead Software Architect',
    employeeName: 'Sarah Jenkins',
    employeeId: 'EMP001',
  },
  {
    id: 'ACT-104',
    timestamp: '3 days ago',
    type: 'EMPLOYEE_DELETED',
    description: 'Archived record for former contractor EMP009',
  },
];
