import React, { useState } from 'react';
import { Employee, AttendanceRecord, Payslip, Report } from '../types';
import { FileText, Download, Printer, Eye, Trash2, Plus, Users, CalendarCheck, Banknote, Building2 } from 'lucide-react';

interface ReportsModuleProps {
  employees: Employee[];
  attendanceRecords: AttendanceRecord[];
  payslips: Payslip[];
  reports: Report[];
  onGenerateReport: (report: Report) => void;
  onDeleteReport: (id: string) => void;
}

export const ReportsModule: React.FC<ReportsModuleProps> = ({ employees, attendanceRecords, payslips, reports, onGenerateReport, onDeleteReport }) => {
  const [filterType, setFilterType] = useState('All');
  const [selectedReport, setSelectedReport] = useState<Report | null>(null);
  const [searchDate, setSearchDate] = useState('');
  
  const generateReport = (type: Report['type']) => {
    const newReport: Report = {
      id: `REP-${Date.now()}`,
      name: `${type} Overview Report`,
      type,
      generatedOn: new Date().toISOString().split('T')[0],
      generatedBy: 'Admin User'
    };
    onGenerateReport(newReport);
  };

  const handleDownload = (report: Report) => {
    // Fake download CSV
    const element = document.createElement("a");
    const file = new Blob([`Report: ${report.name}\nType: ${report.type}\nGenerated On: ${report.generatedOn}\nGenerated By: ${report.generatedBy}`], {type: 'text/csv'});
    element.href = URL.createObjectURL(file);
    element.download = `${report.name.replace(/\s+/g, '_').toLowerCase()}.csv`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const filteredReports = reports.filter(r => {
    const matchType = filterType === 'All' ? true : r.type === filterType;
    const matchDate = searchDate ? r.generatedOn === searchDate : true;
    return matchType && matchDate;
  });

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center space-y-4 sm:space-y-0">
        <div>
          <h2 className="text-2xl font-bold text-slate-800 tracking-tight">Reports Hub</h2>
          <p className="text-sm text-slate-500 mt-1">Generate and export organizational reports.</p>
        </div>

      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <button type="button" onClick={() => generateReport('Employee')} className="bg-white p-4 rounded-2xl border border-slate-200 shadow-sm hover:border-blue-300 hover:shadow-md transition-all flex flex-col items-center justify-center text-center group">
          <div className="w-12 h-12 bg-blue-50 text-blue-600 rounded-xl flex items-center justify-center mb-3 group-hover:scale-110 transition-transform">
            <Users className="w-6 h-6" />
          </div>
          <h3 className="font-bold text-slate-800">Employee Report</h3>
          <p className="text-xs text-slate-500 mt-1">Full workforce details</p>
        </button>
        <button type="button" onClick={() => generateReport('Attendance')} className="bg-white p-4 rounded-2xl border border-slate-200 shadow-sm hover:border-emerald-300 hover:shadow-md transition-all flex flex-col items-center justify-center text-center group">
          <div className="w-12 h-12 bg-emerald-50 text-emerald-600 rounded-xl flex items-center justify-center mb-3 group-hover:scale-110 transition-transform">
            <CalendarCheck className="w-6 h-6" />
          </div>
          <h3 className="font-bold text-slate-800">Attendance Report</h3>
          <p className="text-xs text-slate-500 mt-1">Time & presence logs</p>
        </button>
        <button type="button" onClick={() => generateReport('Salary')} className="bg-white p-4 rounded-2xl border border-slate-200 shadow-sm hover:border-amber-300 hover:shadow-md transition-all flex flex-col items-center justify-center text-center group">
          <div className="w-12 h-12 bg-amber-50 text-amber-600 rounded-xl flex items-center justify-center mb-3 group-hover:scale-110 transition-transform">
            <Banknote className="w-6 h-6" />
          </div>
          <h3 className="font-bold text-slate-800">Salary Report</h3>
          <p className="text-xs text-slate-500 mt-1">Payroll & compensation</p>
        </button>
        <button type="button" onClick={() => generateReport('Department')} className="bg-white p-4 rounded-2xl border border-slate-200 shadow-sm hover:border-purple-300 hover:shadow-md transition-all flex flex-col items-center justify-center text-center group">
          <div className="w-12 h-12 bg-purple-50 text-purple-600 rounded-xl flex items-center justify-center mb-3 group-hover:scale-110 transition-transform">
            <Building2 className="w-6 h-6" />
          </div>
          <h3 className="font-bold text-slate-800">Department Report</h3>
          <p className="text-xs text-slate-500 mt-1">Structure & hierarchy</p>
        </button>
      </div>

      <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
        <div className="p-4 border-b border-slate-100 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
          <span className="font-bold text-slate-800">Generated Reports History</span>
          <div className="flex flex-col sm:flex-row items-center gap-3 w-full sm:w-auto">
            <input 
              type="date" 
              value={searchDate} 
              onChange={(e) => setSearchDate(e.target.value)} 
              className="border border-slate-200 rounded-xl text-sm px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500/20 w-full sm:w-auto text-slate-600"
            />
            <select
              value={filterType}
              onChange={(e) => setFilterType(e.target.value)}
              className="border border-slate-200 rounded-xl text-sm px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500/20 w-full sm:w-auto"
            >
              <option value="All">All Types</option>
              <option value="Employee">Employee</option>
              <option value="Attendance">Attendance</option>
              <option value="Salary">Salary</option>
              <option value="Department">Department</option>
            </select>
          </div>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-slate-50/50 border-b border-slate-200">
                <th className="px-6 py-4 text-xs font-semibold text-slate-500 uppercase tracking-wider">Report Name</th>
                <th className="px-6 py-4 text-xs font-semibold text-slate-500 uppercase tracking-wider">Type</th>
                <th className="px-6 py-4 text-xs font-semibold text-slate-500 uppercase tracking-wider">Generated On</th>
                <th className="px-6 py-4 text-xs font-semibold text-slate-500 uppercase tracking-wider">Generated By</th>
                <th className="px-6 py-4 text-xs font-semibold text-slate-500 uppercase tracking-wider text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200">
              {filteredReports.length > 0 ? (
                filteredReports.map((report) => (
                  <tr key={report.id} className="hover:bg-slate-50/50 transition-colors group">
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-slate-900 flex items-center space-x-3">
                      <FileText className="w-4 h-4 text-slate-400" />
                      <span>{report.name}</span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-medium bg-slate-100 text-slate-700">
                        {report.type}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-600">{report.generatedOn}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-600">{report.generatedBy}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                      <div className="flex items-center justify-end space-x-2">
                        <button type="button" onClick={() => setSelectedReport(report)} className="p-1.5 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-colors" title="View">
                          <Eye className="w-4 h-4" />
                        </button>
                        <button type="button" onClick={() => handleDownload(report)} className="p-1.5 text-slate-400 hover:text-indigo-600 hover:bg-indigo-50 rounded-lg transition-colors" title="Download">
                          <Download className="w-4 h-4" />
                        </button>
                        <button type="button" onClick={() => onDeleteReport(report.id)} className="p-1.5 text-slate-400 hover:text-rose-600 hover:bg-rose-50 rounded-lg transition-colors" title="Delete">
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={5} className="px-6 py-12 text-center text-sm text-slate-500">
                    <div className="flex flex-col items-center justify-center space-y-2">
                      <FileText className="w-8 h-8 text-slate-300" />
                      <p>No reports generated yet.</p>
                    </div>
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {selectedReport && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/50 backdrop-blur-sm">
          <div className="bg-white rounded-2xl shadow-xl w-full max-w-6xl overflow-hidden flex flex-col max-h-[90vh]">
            <div className="p-6 border-b border-slate-100 flex justify-between items-center bg-slate-50">
              <div className="flex items-center space-x-3">
                <div className="p-2 bg-blue-100 text-blue-600 rounded-lg">
                  <FileText className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-slate-800">{selectedReport.name}</h3>
                  <p className="text-xs text-slate-500">ID: {selectedReport.id}</p>
                </div>
              </div>
              <button type="button"
                onClick={() => setSelectedReport(null)}
                className="p-2 text-slate-400 hover:bg-slate-200 rounded-xl transition-colors"
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
              </button>
            </div>
            
            <div className="p-6 overflow-y-auto space-y-6 flex-1 flex flex-col">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4 shrink-0">
                <div className="bg-slate-50 p-4 rounded-xl border border-slate-100">
                  <p className="text-xs text-slate-500 mb-1">Report Type</p>
                  <p className="font-semibold text-slate-700">{selectedReport.type}</p>
                </div>
                <div className="bg-slate-50 p-4 rounded-xl border border-slate-100">
                  <p className="text-xs text-slate-500 mb-1">Generated On</p>
                  <p className="font-semibold text-slate-700">{selectedReport.generatedOn}</p>
                </div>
                <div className="bg-slate-50 p-4 rounded-xl border border-slate-100">
                  <p className="text-xs text-slate-500 mb-1">Generated By</p>
                  <p className="font-semibold text-slate-700">{selectedReport.generatedBy}</p>
                </div>
              </div>

              <div className="border border-slate-200 rounded-xl flex-1 flex flex-col min-h-[400px]">
                <ReportDataViewer report={selectedReport} employees={employees} attendanceRecords={attendanceRecords} payslips={payslips} />
              </div>
            </div>

            <div className="p-6 border-t border-slate-100 bg-slate-50 flex justify-end space-x-3 shrink-0">
              <button type="button"
                onClick={() => setSelectedReport(null)}
                className="px-4 py-2 text-slate-600 hover:bg-slate-200 bg-slate-100 rounded-xl text-sm font-medium transition-colors"
              >
                Close
              </button>
              <button type="button"
                onClick={() => handleDownload(selectedReport)}
                className="flex items-center space-x-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl text-sm font-medium transition-colors shadow-sm"
              >
                <Download className="w-4 h-4" />
                <span>Download CSV</span>
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

const ReportDataViewer: React.FC<{ report: Report, employees: Employee[], attendanceRecords: AttendanceRecord[], payslips: Payslip[] }> = ({ report, employees, attendanceRecords, payslips }) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [filterDept, setFilterDept] = useState('All');

  const depts = ['All', ...Array.from(new Set(employees.map(e => e.department)))];

  if (report.type === 'Employee') {
    const filtered = employees.filter(e => {
      const matchSearch = e.name?.toLowerCase().includes(searchTerm.toLowerCase()) || e.id?.toLowerCase().includes(searchTerm.toLowerCase());
      const matchDept = filterDept === 'All' || e.department === filterDept;
      return matchSearch && matchDept;
    });

    return (
      <div className="flex flex-col h-full bg-white">
        <div className="p-4 border-b border-slate-200 flex flex-col sm:flex-row gap-4 justify-between bg-slate-50">
          <input type="text" placeholder="Search employee..." value={searchTerm} onChange={e => setSearchTerm(e.target.value)} className="px-3 py-2 text-sm border border-slate-200 rounded-lg w-full sm:max-w-xs" />
          <select value={filterDept} onChange={e => setFilterDept(e.target.value)} className="px-3 py-2 text-sm border border-slate-200 rounded-lg">
            {depts.map(d => <option key={d} value={d}>{d}</option>)}
          </select>
        </div>
        <div className="flex-1 overflow-auto">
          <table className="w-full text-left border-collapse min-w-[800px]">
            <thead className="sticky top-0 bg-slate-100 shadow-sm">
              <tr>
                <th className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase">ID</th>
                <th className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase">Name</th>
                <th className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase">Department</th>
                <th className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase">Designation</th>
                <th className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase">Status</th>
                <th className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase">Base Salary</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filtered.length > 0 ? filtered.map(e => (
                <tr key={e.id} className="hover:bg-slate-50">
                  <td className="px-4 py-3 text-sm font-medium">{e.id}</td>
                  <td className="px-4 py-3 text-sm">{e.name}</td>
                  <td className="px-4 py-3 text-sm">{e.department}</td>
                  <td className="px-4 py-3 text-sm">{e.designation}</td>
                  <td className="px-4 py-3 text-sm">{e.status}</td>
                  <td className="px-4 py-3 text-sm">${e.basicSalary.toLocaleString()}</td>
                </tr>
              )) : (
                <tr><td colSpan={6} className="p-8 text-center text-slate-500">No records found</td></tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    );
  }

  if (report.type === 'Attendance') {
    const filtered = attendanceRecords.filter(a => {
      const emp = employees.find(e => e.id === a.employeeId);
      const matchSearch = emp?.name?.toLowerCase().includes(searchTerm.toLowerCase()) || a.date?.includes(searchTerm);
      return matchSearch;
    });

    return (
      <div className="flex flex-col h-full bg-white">
        <div className="p-4 border-b border-slate-200 flex gap-4 bg-slate-50">
          <input type="text" placeholder="Search by name or date (YYYY-MM-DD)..." value={searchTerm} onChange={e => setSearchTerm(e.target.value)} className="px-3 py-2 text-sm border border-slate-200 rounded-lg w-full max-w-sm" />
        </div>
        <div className="flex-1 overflow-auto">
          <table className="w-full text-left border-collapse min-w-[800px]">
            <thead className="sticky top-0 bg-slate-100 shadow-sm">
              <tr>
                <th className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase">Date</th>
                <th className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase">Employee</th>
                <th className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase">Status</th>
                <th className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase">Check In</th>
                <th className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase">Check Out</th>
                <th className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase">Hours</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filtered.length > 0 ? filtered.map(a => {
                const emp = employees.find(e => e.id === a.employeeId);
                return (
                  <tr key={a.id} className="hover:bg-slate-50">
                    <td className="px-4 py-3 text-sm font-medium">{a.date}</td>
                    <td className="px-4 py-3 text-sm">{emp?.name || a.employeeId}</td>
                    <td className="px-4 py-3 text-sm">{a.status}</td>
                    <td className="px-4 py-3 text-sm">{a.checkInTime}</td>
                    <td className="px-4 py-3 text-sm">{a.checkOutTime}</td>
                    <td className="px-4 py-3 text-sm">{a.workingHours}</td>
                  </tr>
                );
              }) : (
                <tr><td colSpan={6} className="p-8 text-center text-slate-500">No records found</td></tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    );
  }

  if (report.type === 'Salary') {
    const filtered = payslips.filter(p => {
      const emp = employees.find(e => e.id === p.employeeId);
      const matchSearch = emp?.name?.toLowerCase().includes(searchTerm.toLowerCase()) || p.month?.includes(searchTerm);
      return matchSearch;
    });

    return (
      <div className="flex flex-col h-full bg-white">
        <div className="p-4 border-b border-slate-200 flex gap-4 bg-slate-50">
          <input type="text" placeholder="Search by name or month (YYYY-MM)..." value={searchTerm} onChange={e => setSearchTerm(e.target.value)} className="px-3 py-2 text-sm border border-slate-200 rounded-lg w-full max-w-sm" />
        </div>
        <div className="flex-1 overflow-auto">
          <table className="w-full text-left border-collapse min-w-[800px]">
            <thead className="sticky top-0 bg-slate-100 shadow-sm">
              <tr>
                <th className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase">Month</th>
                <th className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase">Employee</th>
                <th className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase">Basic</th>
                <th className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase">Earnings</th>
                <th className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase">Deductions</th>
                <th className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase">Net Salary</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filtered.length > 0 ? filtered.map(p => {
                const emp = employees.find(e => e.id === p.employeeId);
                return (
                  <tr key={p.id} className="hover:bg-slate-50">
                    <td className="px-4 py-3 text-sm font-medium">{p.month}</td>
                    <td className="px-4 py-3 text-sm">{emp?.name || p.employeeId}</td>
                    <td className="px-4 py-3 text-sm">${p.basicSalary.toLocaleString()}</td>
                    <td className="px-4 py-3 text-sm">${p.totalEarnings.toLocaleString()}</td>
                    <td className="px-4 py-3 text-sm">${p.totalDeductions.toLocaleString()}</td>
                    <td className="px-4 py-3 text-sm font-bold text-slate-900">${p.netSalary.toLocaleString()}</td>
                  </tr>
                );
              }) : (
                <tr><td colSpan={6} className="p-8 text-center text-slate-500">No records found</td></tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    );
  }

  if (report.type === 'Department') {
    const deptStats = depts.filter(d => d !== 'All' && d.toLowerCase().includes(searchTerm.toLowerCase())).map(d => {
      const emps = employees.filter(e => e.department === d);
      const activeEmps = emps.filter(e => e.status === 'Active');
      const avgSalary = emps.length > 0 ? emps.reduce((acc, curr) => acc + curr.basicSalary, 0) / emps.length : 0;
      return { dept: d, total: emps.length, active: activeEmps.length, avgSalary };
    });

    return (
      <div className="flex flex-col h-full bg-white">
        <div className="p-4 border-b border-slate-200 flex gap-4 bg-slate-50">
          <input type="text" placeholder="Search department..." value={searchTerm} onChange={e => setSearchTerm(e.target.value)} className="px-3 py-2 text-sm border border-slate-200 rounded-lg w-full max-w-sm" />
        </div>
        <div className="flex-1 overflow-auto">
          <table className="w-full text-left border-collapse min-w-[800px]">
            <thead className="sticky top-0 bg-slate-100 shadow-sm">
              <tr>
                <th className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase">Department</th>
                <th className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase">Total Employees</th>
                <th className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase">Active Employees</th>
                <th className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase">Average Basic Salary</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {deptStats.length > 0 ? deptStats.map(d => (
                <tr key={d.dept} className="hover:bg-slate-50">
                  <td className="px-4 py-3 text-sm font-medium">{d.dept}</td>
                  <td className="px-4 py-3 text-sm">{d.total}</td>
                  <td className="px-4 py-3 text-sm">{d.active}</td>
                  <td className="px-4 py-3 text-sm">${Math.round(d.avgSalary).toLocaleString()}</td>
                </tr>
              )) : (
                <tr><td colSpan={4} className="p-8 text-center text-slate-500">No records found</td></tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    );
  }

  return null;
};
